package com.dreamsoftware.inquize.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1E88E5) // Electric Blue
val md_theme_light_onPrimary = Color(0xFFFFFFFF) // White for contrast on primary text
val md_theme_light_primaryContainer = Color(0xFFBBDEFB) // Light Blue for primary containers
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1) // Darker Blue for readability in containers
val md_theme_light_secondary = Color(0xFF388E3C) // Green for secondary elements
val md_theme_light_onSecondary = Color(0xFFFFFFFF) // White for text on secondary elements
val md_theme_light_secondaryContainer = Color(0xFFA5D6A7) // Light Green for secondary containers
val md_theme_light_onSecondaryContainer = Color(0xFF1B5E20) // Dark Green for text in secondary containers
val md_theme_light_tertiary = Color(0xFFE87E42) // Vibrant Orange for tertiary elements
val md_theme_light_onTertiary = Color(0xFFFFFFFF) // White for contrast on tertiary text
val md_theme_light_tertiaryContainer = Color(0xFFFFE0B2) // Light Orange for tertiary containers
val md_theme_light_onTertiaryContainer = Color(0xFF3E2723) // Dark Brown for text in tertiary containers
val md_theme_light_error = Color(0xFFBA1A1A) // Red for errors
val md_theme_light_errorContainer = Color(0xFFFFCDD2) // Light Red for error containers
val md_theme_light_onError = Color(0xFFFFFFFF) // White for error text
val md_theme_light_onErrorContainer = Color(0xFF410002) // Dark Red for text in error containers
val md_theme_light_background = Color(0xFFFFFFFF) // White for background
val md_theme_light_onBackground = Color(0xFF1B1B1F) // Dark Gray for background text
val md_theme_light_surface = Color(0xFFF2F5FA) // Light surface color
val md_theme_light_onSurface = Color(0xFF1B1B1F) // Text on light surfaces
val md_theme_light_surfaceVariant = Color(0xFFE0E0E0) // Variant surface color for section differentiation
val md_theme_light_onSurfaceVariant = Color(0xFF46464F) // Text on surface variant
val md_theme_light_outline = Color(0xFF757575) // Color for outlines
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4) // Inverse text on surfaces
val md_theme_light_inverseSurface = Color(0xFF313034) // Inverse surface color
val md_theme_light_inversePrimary = Color(0xFF90CAF9) // Inverse variant of primary color
val md_theme_light_shadow = Color(0xFF000000) // Shadow color
val md_theme_light_surfaceTint = Color(0xFF1E88E5) // Tint for surfaces
val md_theme_light_outlineVariant = Color(0xFFBDBDBD) // Outline variant color
val md_theme_light_scrim = Color(0xFF000000) // Background shadow color

val md_theme_dark_primary = Color(0xFF1E88E5) // Electric Blue
val md_theme_dark_onPrimary = Color(0xFF0D47A1) // Darker Blue for primary text
val md_theme_dark_primaryContainer = Color(0xFF1565C0) // Medium Blue for primary containers in dark theme
val md_theme_dark_onPrimaryContainer = Color(0xFFE3F2FD) // Light Blue for text in primary containers
val md_theme_dark_secondary = Color(0xFF388E3C) // Green for secondary elements
val md_theme_dark_onSecondary = Color(0xFF1B5E20) // Dark Green for secondary text
val md_theme_dark_secondaryContainer = Color(0xFF2E7D32) // Medium Green for secondary containers
val md_theme_dark_onSecondaryContainer = Color(0xFFC8E6C9) // Light Green for text in secondary containers
val md_theme_dark_tertiary = Color(0xFFE87E42) // Vibrant Orange for tertiary elements
val md_theme_dark_onTertiary = Color(0xFF5D4037) // Dark Brown for tertiary text
val md_theme_dark_tertiaryContainer = Color(0xFFD84315) // Dark Orange for tertiary containers
val md_theme_dark_onTertiaryContainer = Color(0xFFFFF3E0) // Very Light Orange for text in tertiary containers
val md_theme_dark_error = Color(0xFFFFB4AB) // Red for errors in dark theme
val md_theme_dark_errorContainer = Color(0xFF93000A) // Dark Red for error containers
val md_theme_dark_onError = Color(0xFF690005) // Darker text for errors
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6) // Light Red for text in error containers
val md_theme_dark_background = Color(0xFF121212) // Black for background
val md_theme_dark_onBackground = Color(0xFFECEFF1) // Light Gray for text on background
val md_theme_dark_surface = Color(0xFF1C1C1E) // Dark surface color
val md_theme_dark_onSurface = Color(0xFFECEFF1) // Light Gray for text on surfaces
val md_theme_dark_surfaceVariant = Color(0xFF424242) // Variant surface color for section differentiation
val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD) // Text on surface variant
val md_theme_dark_outline = Color(0xFF757575) // Color for outlines
val md_theme_dark_inverseOnSurface = Color(0xFF121212) // Inverse text on surfaces
val md_theme_dark_inverseSurface = Color(0xFFECEFF1) // Inverse surface color
val md_theme_dark_inversePrimary = Color(0xFF64B5F6) // Inverse variant of primary color
val md_theme_dark_shadow = Color(0xFF000000) // Shadow color
val md_theme_dark_surfaceTint = Color(0xFF1E88E5) // Tint for surfaces
val md_theme_dark_outlineVariant = Color(0xFF616161) // Outline variant color
val md_theme_dark_scrim = Color(0xFF000000) // Background shadow color