package com.dreamsoftware.inquize.domain.chat

import java.util.UUID


/**
 * Represents a single chat message in a conversation.
 *
 * @property message the text content of the message.
 * @property role the [Role] of the message sender.
 * @property id A unique identifier for the message, automatically generated by default.
 */
data class ChatMessage(
    val message: String,
    val role: Role,
    val id: String = UUID.randomUUID().toString()
) {
    /**
     * Represents all the possible roles of a message sender.
     */
    enum class Role {
        /**
         * Represents a message sent by the user.
         */
        USER,

        /**
         * Represents a message sent by the assistant.
         */
        ASSISTANT
    }
}